# Generated by Django 5.1.2 on 2024-12-05 06:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='clientes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_cliente', models.CharField(max_length=20)),
                ('apellido_cliente', models.CharField(max_length=20)),
                ('email_cliente', models.CharField(max_length=30)),
                ('telefono_cliente', models.IntegerField(max_length=20)),
                ('contrasena', models.CharField(max_length=30)),
            ],
        ),
    ]
