# Generated by Django 5.1.2 on 2024-12-05 22:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_carritoventas_productos_rolesusuarios_usuarios_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='RolesUsuarios',
            new_name='RolesTrabajadores',
        ),
        migrations.RenameModel(
            old_name='Usuarios',
            new_name='Trabajadores',
        ),
    ]
